### ISSUE TITLE
You checked in some iCloud proxies instead of project & workspace

### ISSUE THREAD

**Issue by danwood** [Ge0rges/Synaction#1]
Hi, I'm interested in this project but I noticed that you checked in two files `.Synaction.xcodeproj.icloud` and `.Synaction.xcworkspace.icloud` which might be proxies for the actual files that might be stored on iCloud Drive. Could you check in the actual project and workspace? Might help the next person along …

**Comment by Ge0rges** [comment]
Fixed hopefully.
